PREFIX=/usr/local
BUILD_TOOL=xcodebuild

EXECUTABLE_NAME=carthage-input-files
PROJECT_NAME=CarthageInputFiles
XCODEFLAGS=-project $(PROJECT_NAME).xcodeproj

CARTHAGEINPUTFILES_EXECUTABLE=./build/Release/$(PROJECT_NAME)

SWIFT_COMMAND=/usr/bin/swift
SWIFT_BUILD_COMMAND=$(SWIFT_COMMAND) build
SWIFT_TEST_COMMAND=$(SWIFT_COMMAND) test

build:
	$(SWIFT_BUILD_COMMAND)

test:
	$(SWIFT_TEST_COMMAND)

install:
	$(BUILD_TOOL) $(XCODEFLAGS)
	mkdir -p $(PREFIX)/bin
	cp -f $(CARTHAGEINPUTFILES_EXECUTABLE) $(PREFIX)/bin/$(EXECUTABLE_NAME)

uninstall:
	rm -f $(PREFIX)/bin/$(EXECUTABLE_NAME)
